### ISSUE TITLE
Error encountered using yeti 5.0

### ISSUE THREAD

**Issue by helmutgiese** [mittelmark/yeti#1]
Hi Detlef, 
when using your version with the files I copied from the page 'Parsing C types' on Tcl's wiki I got the following error:
missing close-brace: possible unbalanced brace in comment
    while executing
"itcl::class CParser {"
    (file "tmp/cparser.tcl" line 13)
    invoked from within
"source tmp/$file.tcl"
    ("foreach" body line 11)
    invoked from within
"foreach {file class} {cscanner CScannerGenerator cparser CParserGenerator} {
    if {![file exists tmp/$file.tcl]
     || [file mtime $file.tcl] > [fi..."
    (file "driver.tcl" line 221)

Wenn I used my previous version of Yeti the error was gone.
Maybe you can have a look.
Best regards
Helmut
PS: My email address is hgiese@ratiosoft.com

**Comment by mittelmark** [comment]
Hmm, I have as well with yeti-0.4.1, the oldest version I have, the same error, the problem is in the array yytrans which contains a lot of very likely unbalanced braces. Could you send me your yeti version which does not have this error.

**Comment by mittelmark** [comment]
In LUCK, http://www.ch-werner.de/cgi-bin/luck.pl , I found version 0.4.2. this contains my bugifx for ylex.tcl and a bugfix for yeti.tcl which should covers the cparser.tcl problem, at least I can create now the cparser using this version which is now on my repo here, To avoid confusion I give it the same version numbers as the version you get from LUCK.
